### ISSUE TITLE
 real-world-examples-of-genetic-algorithms

### ISSUE THREAD

**Issue by Eoghan-K** [joshuacassidy/genetic-algorithms#1]
@joshuacassidy The genetic algorithms looks pretty cool. I'm curious to know of what are some applications where this can be used in the real world?

**Comment by joshuacassidy** [comment]
Hi @Eoghan-K, 

That is a great question. The purpose of Genetic Algorithms is to solve search and optimization problems by using metaheuristics that follow the concept of survival of the fittest. These algorithms are in the field of local search optimization (the hill-climbing algorithm is another example of this which I have done an implementation on https://github.com/joshuacassidy/Hill-Climbing). 
Some fun examples of how genetic algorithms have been used are:
Computation Intelligence Car Evolution: http://boxcar2d.com/index.html
Maze Solving: https://www.youtube.com/watch?v=mec7fYHH5u0
Teaching an object to jump over a ball: https://www.youtube.com/watch?v=Gl3EjiVlz_4

Other examples include: making optimizations for algorithms in game theory e.g minimax which is used in tic-tac-toe, image processing or creating timetables for a university

Genetic algorithms can also be used for code breaking which I have created an example project for https://github.com/joshuacassidy/genetic-code-breaker

I hope this answers your question @Eoghan-K.

Kind regards,
Joshua Cassidy
